name: "[DevX] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 9AM, Mondays to Fridays
    - cron: "0 9 * * MON-FRI"

jobs:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.main.outputs.repos }}
    steps:
      - id: main
        # See https://github.com/orgs/guardian/teams/developer-experience/repositories
        run: |
          # TODO handle these correctly, maybe via https://github.com/guardian/actions-read-private-repos?
          PRIVATE_REPOS=(
            aws-account-setup
            aws-cost-management
            cdk-metadata
            cfn-private-resource-types
            deploy-tools-platform
            devx-docs
            dns-validation-lambda
            github-audit
            google-chat-bots
            grafana
            janus
            private-infrastructure-config
            security-platform
            service-control-policies
            toil-records
            tracker
          )
        
          PUBLIC_REPOS=(
            actions-read-private-repos
            actions-riff-raff
            amiable
            amigo
            anghammarad
            cdk
            cdk-playground
            cloudformation-information
            cloudwatch-logs-management
            devx-config
            devx-logs
            elastic-search-monitor
            elasticsearch-node-rotation
            github-lens
            instance-tag-discovery
            janus-app
            node-riffraff-artifact
            prism
            riff-raff
            sbt-riffraff-artifact
            security-hq
            ssm-to-env
            toil
          )
          
          RESULT=""
          for repo in "${PUBLIC_REPOS[@]}"; do
            RESULT="$RESULT,guardian/$repo"
          done
          
          # remove leading ,
          RESULT="${RESULT:1}"
          echo "::set-output name=repos::$RESULT"
  prnouncer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: guardian/actions-prnouncer@main
        with:
          # https://user-images.githubusercontent.com/21217225/191922153-ae6fcebe-ca87-4611-93ee-0e66a47dab5d.png
          # Anybody can create a new Webhook for a google chatroom, press the caret by the Space name and press "Manage Webhooks"
          # You can use any value for the name and avatar URL. You should add this secret to your repository settings.
          google-webhook-url: ${{ secrets.DEVX_GOOGLE_WEBHOOK_URL }}

          # Defaults to the repository that this action is configured in.
          # You can specify multiple repositories by using a comma delimited string!
          github-repositories: ${{ needs.setup.outputs.repos }}

          # Comma delimited list of user ID's to ignore when scanning for pull requests. Defaults to Dependabot
          # github-ignored-users: 49699333

          # Comma delimited list of labels to ignore when scanning for pull requests. Defaults to "Stale".
          # I recommend setting up the Stale PR workflow if you want to use this action.
          # github-ignored-labels: stale
