name: "[DevX] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 9AM, Mondays to Fridays
    - cron: "0 9 * * MON-FRI"

jobs:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.main.outputs.repos }}
    steps:
      - id: main
        # See https://github.com/orgs/guardian/teams/developer-experience/repositories
        run: |
          PRIVATE_REPOS=(
            aws-account-setup
            aws-cost-management
            cdk-metadata
            cfn-private-resource-types
            deploy-tools-platform
            devx-docs
            dns-validation-lambda
            github-audit
            google-chat-bots
            grafana
            private-infrastructure-config
            security-platform
            service-control-policies
            toil-records
            tracker
          )
        
          PUBLIC_REPOS=(
            actions-read-private-repos
            actions-riff-raff
            amiable
            amigo
            anghammarad
            cdk
            cdk-playground
            cloudformation-information
            cloudwatch-logs-management
            devx-config
            devx-logs
            elastic-search-monitor
            elasticsearch-node-rotation
            github-lens
            instance-tag-discovery
            janus-app
            node-riffraff-artifact
            prism
            riff-raff
            sbt-riffraff-artifact
            security-hq
            ssm-to-env
            toil
          )
          
          REPOS=("${PRIVATE_REPOS[@]}" "${PUBLIC_REPOS[@]}")
          
          RESULT=""
          for repo in "${REPOS[@]}"; do
            RESULT="$RESULT,guardian/$repo"
          done
          
          # remove leading ,
          RESULT="${RESULT:1}"
          echo "::set-output name=repos::$RESULT"
  prnouncer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.DEVX_GOOGLE_WEBHOOK_URL }}
          github-repositories: ${{ needs.setup.outputs.repos }}

          # This is a fine-grained PAT for the guardian-ci user.
          # It's got PR read permission for all repositories accessible by the user.
          # See https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/
          github-token: ${{ secrets.GU_REPO_READ_ACCESS }}
