name: "[DevX SOaR] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 7AM, Mondays to Fridays
    - cron: "0 7 * * MON-FRI"

jobs:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.main.outputs.repos }}
    steps:
      - id: main
        # See https://github.com/orgs/guardian/teams/developer-experience/repositories
        run: |
          REPOS=(
            .github
            actions-read-private-repos
            actions-riff-raff
            amiable
            amigo
            amiup
            anghammarad
            aws-account-setup
            aws-cost-management
            cdk
            cdk-playground
            cfn-private-resource-types
            cloudformation-information
            cloudwatch-logs-management
            cognito-auth-lambdas
            deploy-tools-platform
            devx-config
            devx-docs
            devx-logs
            dns-validation-lambda
            elastic-search-monitor
            elasticsearch-node-rotation
            github-audit
            grafana
            instance-tag-discovery
            janus-app
            master-to-main
            node-riffraff-artifact
            privatebin-docker
            private-infrastructure-config
            prism
            riff-raff
            sbt-riffraff-artifact
            security-hq
            security-platform
            service-catalogue
            simple-configuration
            snyk-tag-monitor
            ssm-scala
            ssm-to-env
            toil
            toil-records
            tracker
            waf
          )

          RESULT=""
          for repo in "${REPOS[@]}"; do
            RESULT="$RESULT,guardian/$repo"
          done

          # remove leading ,
          RESULT="${RESULT:1}"
          echo "repos=$RESULT" >> $GITHUB_OUTPUT
  prnouncer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Use GitHub App Token
        uses: wow-actions/use-app-token@d7957e08172ca2e8e49b35b8d266ad585885edc7
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }} # The ID of the GitHub App
          private_key: ${{ secrets.PRIVATE_KEY }} # The private key of the GitHub App
          fallback: ${{ secrets.GITHUB_TOKEN }} # fall back to the default token if the app token is not available

      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.DEVX_GOOGLE_WEBHOOK_URL }}
          github-repositories: ${{ needs.setup.outputs.repos }}
          github-token: ${{ steps.generate_token.outputs.BOT_TOKEN }} # A GitHub app token generated by the previous step

          # By default, guardian/actions-prnouncer doesn't report PRs from Dependabot. Include them here.
          github-ignored-users: ''
