name: "[DevX SOaR] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 7AM, Mondays to Fridays
    - cron: "0 7 * * MON-FRI"

jobs:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.main.outputs.repos }}
    steps:
      - id: main
        # See https://github.com/orgs/guardian/teams/developer-experience/repositories
        run: |
          REPOS=(
            actions-read-private-repos
            actions-riff-raff
            amiable
            amigo
            anghammarad
            aws-account-setup
            aws-cost-management
            cdk
            cdk-metadata
            cdk-playground
            cfn-private-resource-types
            cloudformation-information
            cloudwatch-logs-management
            deploy-tools-platform
            devx-config
            devx-docs
            devx-logs
            dns-validation-lambda
            elastic-search-monitor
            elasticsearch-node-rotation
            github-audit
            github-lens
            google-chat-bots
            grafana
            instance-tag-discovery
            janus-app
            node-riffraff-artifact
            private-infrastructure-config
            prism
            riff-raff
            sbt-riffraff-artifact
            security-hq
            security-platform
            service-control-policies
            ssm-to-env
            toil
            toil-records
            tracker
          )

          RESULT=""
          for repo in "${REPOS[@]}"; do
            RESULT="$RESULT,guardian/$repo"
          done

          # remove leading ,
          RESULT="${RESULT:1}"
          echo "repos=$RESULT" >> $GITHUB_OUTPUT
  prnouncer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.DEVX_GOOGLE_WEBHOOK_URL }}
          github-repositories: ${{ needs.setup.outputs.repos }}

          # This is a fine-grained PAT for the guardian-ci user.
          # It's got PR read permission for all repositories accessible by the user.
          # See https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/
          github-token: ${{ secrets.GU_REPO_READ_ACCESS }}

          # By default, guardian/actions-prnouncer doesn't report PRs from Dependabot. Include them here.
          github-ignored-users: ''
