name: "[Fairground] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 6AM, Mondays to Fridays
    - cron: "0 6 * * MON-FRI"

jobs:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.main.outputs.repos }}
    steps:
      - id: main
        run: |
          REPOS=(
            frontend
            dotcom-rendering
            facia-tool
          )

          RESULT=""
          for repo in "${REPOS[@]}"; do
            RESULT="$RESULT,guardian/$repo"
          done

          # remove leading ,
          RESULT="${RESULT:1}"
          echo "repos=$RESULT" >> $GITHUB_OUTPUT
  prnouncer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Use GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # These values are for the GitHub App "Gu PRnouncer config"
          # See https://github.com/organizations/guardian/settings/apps/gu-prnouncer-config (only accessible by GitHub owners)
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: guardian

      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.FAIRGROUND_GOOGLE_WEBHOOK_URL }}
          github-repositories: ${{ needs.setup.outputs.repos }}
          github-token: ${{ steps.app-token.outputs.token }} # A GitHub app token generated by the previous step

          github-ignored-users: ""
          github-announced-users: 20416599,43961396,102960844 
          github-ignored-labels: Stale,prnouncer-ignore
          show-pr-age: "true"
