name: "[Interviews] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 9AM, Mondays to Fridays
    - cron: "0 9 * * MON-FRI"

jobs:
  prnouncer:
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.INTERVIEWS_GOOGLE_WEBHOOK_URL }}
          github-repositories: guardian/coding-exercises,guardian/coding-exercise-project,guardian/interview-questions
          github-token: ${{ secrets.GU_REPO_READ_ACCESS }}
