name: "[Interviews] Google Chats PR Announcer"

on:
  workflow_dispatch:
  schedule:
    # Every morning at 9AM, Mondays to Fridays
    - cron: "0 9 * * MON-FRI"

jobs:
  prnouncer:
    runs-on: ubuntu-latest
    steps:
      - name: Use GitHub App Token
        uses: wow-actions/use-app-token@d7957e08172ca2e8e49b35b8d266ad585885edc7
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }} # The ID of the GitHub App
          private_key: ${{ secrets.PRIVATE_KEY }} # The private key of the GitHub App
          fallback: ${{ secrets.GITHUB_TOKEN }} # fall back to the default token if the app token is not available

      - uses: guardian/actions-prnouncer@main
        with:
          google-webhook-url: ${{ secrets.INTERVIEWS_GOOGLE_WEBHOOK_URL }}
          github-repositories: guardian/coding-exercises,guardian/coding-exercise-project,guardian/interview-questions,guardian/redact-pdf
          github-token: ${{ steps.generate_token.outputs.BOT_TOKEN }} # A GitHub app token generated by the previous step
